### ISSUE TITLE
Use Windows rather than Views?

### ISSUE THREAD

**Issue by abgreen29** [manumaticx/Ti.DrawerLayout#64] opened 2016-04-22 12:12 UTC
Hi there,

Great work on this, thanks!

I'm wondering if there is any way to use Windows rather than Views for content? Could I use separate Windows and just add the drawer to each one as it opens?

**Comment by manumaticx** [comment] 2016-04-22 18:09
You mean Windows as contentViews? This is not going to work.

**Comment by abgreen29** [comment] 2016-04-23 01:05
No, since you have to create a Window first that the drawer is added to, can I create a drawer that only has a leftView, but the main content is in the Window that the drawer is added to? Then each menu selection in the drawer would open a new Window, and the drawer would be added again to each new Window. Do you see any issues with this?

The reason I'm thinking this way is to simplify my cross-platform app. For iOS, I need to use Windows otherwise the NavigationWindow doesn't work. If I have to use Windows for iOS and Views for Android, it makes my app more difficult to maintain as I have to write more device-specific code.

**Comment by manumaticx** [comment] 2016-04-23 12:58
Have you seen this drawer widget? https://github.com/FokkeZB/nl.fokkezb.drawer

In the readme, Fokke also describes how to solve the View / Window problem. Maybe this is what you are looking for?

**Comment by manumaticx** [comment] 2016-04-28 10:02
Ah! Now I get what your question is about. Sorry, it took a while :D 

Let me think about this.... I actually never tried this, have you? I'm going to test this soon and let you know!

**Comment by manumaticx** [comment] 2016-04-28 10:19
@abgreen29 Hey this actually works fine. But events aren't bubbled to the parent window. I'll try to figure out what the problem is

**Comment by abgreen29** [comment] 2016-04-28 12:37
Thanks for looking at this! Haven't really had a chance to try it myself yet.

**Comment by manumaticx** [comment] 2016-04-28 12:50
I'm closing this issue. I'll try to fix the event issue in next version, reported as #66

**Closed by manumaticx** 2016-04-28 12:50 UTC
Labels: question
